version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Dependency Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Cache Dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn audit
      - run: yarn build
      - run: yarn prettier:check
      - run: yarn test:lint
      - run: yarn test:html
      - run: yarn test:vue
      - run: yarn test:unit:ci
      - run: yarn test:unit:coverage
